### ISSUE TITLE
OnTap() does not get triggered for CirculitoSection in iOS example app. Version : ^1.0.0

### ISSUE THREAD

**Issue by tashiwangdi** [kegadev/circulito#1]
Is it a known issue that the onTap is not triggered for CirculitoSection in iOS devices/simulators?
The same app in Android responds to onTap gesture.

**Comment by tashiwangdi** [comment]
@kegadev : Is it a known issue ?

**Comment by kegadev** [comment]
Hi there @tashiwangdi. I haven't noticed that, thanks for letting me know. I checked myself and it's true. 
I've been busy this days with other projects, but as soon as I get a free time I put an eye on it and see what is going on.

**Comment by kegadev** [comment]
Hi @tashiwangdi. I just updated the package now, fixing the OnTap on mobiles. Thanks for letting me know that issue. Now I will close this issue.
